### ISSUE TITLE
How to enable mines?

### ISSUE THREAD

**Issue by hipoglucido** [Noswis/SpaceFortress#4]
Hi, I am using the Space Fortress interface of your code and I would like to know enable the mines back for the SF_Cairo version. I see that there is no parameter for specifying that so I guess that the C++ code needs to be modified. Any idea which parts of the code should be un-commented?

Thanks!

**Comment by DerkBarten** [comment]
Hello,

I'm sorry for the late response. Me and my team who worked in this project last year actually did not comment out all that stuff.  That is done by our predecessors; who first worked on the project and made quite a mess of the code :sweat_smile: . So basically, I don't know where the mines are handled in the code. However, after a quick search, some of the mine logic seems to be present in Game/SF_Cairo/TCOL.c  although commented out. Also, in the other C files, there is a lot of commented out code referencing mines. I recommend you to CTRL-F  all C files in Game/SF_Cairo and uncomment all things referencing to mines. I think this should reenable the mines.

The Best of Luck,

Derk

**Comment by hipoglucido** [comment]
Yeah that is exactly what I did. Thanks!
